apiVersion: apps/v1
kind: Deployment
metadata:
  name: invoice-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: invoice-backend
  template:
    metadata:
      labels:
        app: invoice-backend
    spec:
      containers:
      - name: backend
        image: hakkibate/invoice-backend:latest
        ports:
        - containerPort: 8080
