# =====================================================
# 🌐 Kubernetes Service zum Verbinden von Frontend & Backend
# =====================================================
# Services stellen sicher, dass Pods über stabile IPs & DNS erreichbar sind
# und (optional) von außen erreichbar gemacht werden können.

apiVersion: v1
kind: Service
metadata:
  name: invoice-service               # Name des Services
spec:
  type: LoadBalancer                  # Exponiert die App nach außen (Hetzner Load Balancer)
  selector:
    app: invoice-frontend             # Wählt alle Pods mit diesem Label (Frontend)
  ports:
    - name: http
      port: 80                        # Öffentlicher Port (außen sichtbar)
      targetPort: 3000                # Leitet Traffic an Container-Port des Frontends

---

apiVersion: v1
kind: Service
metadata:
  name: invoice-backend-service      # Name des Backend-Service
spec:
  type: ClusterIP                    # nur intern erreichbar (vom Frontend aus)
  selector:
    app: invoice-backend             # muss mit labels aus backend-deployment.yaml übereinstimmen
  ports:
    - protocol: TCP
      port: 8000                     # Port für FastAPI
      targetPort: 8000               # Container-Port für FastAPI